# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sudo add-apt-repository ppa:mhier/libboost-latest
          sudo apt update
          sudo apt install libboost1.68-dev
          cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake
          sudo apt-get install -y valgrind
          cd /usr/src/gtest/
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
          cd $PROJECT_DIR
          mkdir build
          cd build
          cmake ../project/
          make
          valgrind tests/ut/runTests
          python3 ../project/tests/sct/tests.py
